In [2]:
import numpy as  np


create
basic opration
math opration
indexing and slicing
boolean filter

In [3]:
x =np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [4]:
a =  np.array([[1,2,3],[1,2,3]])
print(a)
print(a.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [6]:
b = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(b)
print(b.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


In [7]:
z = [0,1,2,3,4,5,6,7,8,9]
nz = np.array([z]*10)
print(nz)
print(nz.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(10, 10)


- random
- arrange
- linspace

In [8]:
np.random.rand(3,3)

array([[0.44674683, 0.73089782, 0.55649085],
       [0.81376417, 0.30553754, 0.52923033],
       [0.79608287, 0.28298471, 0.16711237]])

In [10]:
r1 = np.random.randint(-5,6,(5,5))
print(r1)

[[ 1  0  2  5 -4]
 [ 1 -3 -5  2  2]
 [ 5  5 -1 -2 -2]
 [ 4  1  0 -2 -1]
 [-4 -2  2 -3 -3]]


In [13]:
# start ,stop ,gap
np.arrange(0,50, .5)

AttributeError: module 'numpy' has no attribute 'arrange'

In [14]:
# start, stop, number_of_iyem
np.linspace(0, 50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

array attributes
- shape
- ditype
- ndim
- size


basic opration
 - sum
 - mean 
 - min
 - max
 - std
 - reshape
 - transpose  
 - flatten


In [15]:
x.dtype

dtype('int64')

In [16]:
x = np.random.rand(3,3)
x.dtype

dtype('float64')

In [17]:
x.ndim

2

In [18]:
z = np.random.randint(1,5,(3,3,3))
z.ndim

3

In [19]:
z.size

27

In [20]:
z.sum()

np.int64(73)

In [27]:
a = np.random.rand(2,3)
print(a.sum())
print(a.sum(axis=0)) # columm wise
print(a.sum(axis=1)) # row wise
print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())
# all the methods can be used with axis

3.863008629311017
[0.99012113 1.39910431 1.47378319]
[2.55493785 1.30807078]
0.6438347715518361
0.9507586292655594
0.04797634271050699
0.3060113031093505
0.09364291763068276


In [29]:
z = np.random.randint(11,99,(5,5))
print(z)
print('transpose')
print(z.transpose()) # or print(z.t)
print('flattened')
print(z.flatten())

[[36 45 24 73 71]
 [76 49 52 84 47]
 [79 61 33 51 36]
 [67 16 75 34 34]
 [23 61 88 27 98]]
transpose
[[36 76 79 67 23]
 [45 49 61 16 61]
 [24 52 33 75 88]
 [73 84 51 34 27]
 [71 47 36 34 98]]
flattened
[36 45 24 73 71 76 49 52 84 47 79 61 33 51 36 67 16 75 34 34 23 61 88 27
 98]


In [31]:
a = np.random.randint(1,10,(4,5))
print(a)
print(a.reshape(20))
print(a.reshape(2,10))
print(a.reshape(10,2))

[[5 5 9 3 7]
 [3 9 6 3 3]
 [4 6 8 2 1]
 [2 7 9 7 2]]
[5 5 9 3 7 3 9 6 3 3 4 6 8 2 1 2 7 9 7 2]
[[5 5 9 3 7 3 9 6 3 3]
 [4 6 8 2 1 2 7 9 7 2]]
[[5 5]
 [9 3]
 [7 3]
 [9 6]
 [3 3]
 [4 6]
 [8 2]
 [1 2]
 [7 9]
 [7 2]]


In [32]:
a= np.array([[1,2],[3,4]])
b = np.array([[6,2],[6,3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[6 2]
 [6 3]]


In [33]:
# whwn using 2 matrix  the shape must be yhe same
print(a+b)
print(a-b)
print(a/b) # element wise division
print(a*b) # element wise multiplictaion
print(a@b) # matrix multiplication
print(a.dot(b)) # matrix multiplication

[[7 4]
 [9 7]]
[[-5  0]
 [-3  1]]
[[0.16666667 1.        ]
 [0.5        1.33333333]]
[[ 6  4]
 [18 12]]
[[18  8]
 [42 18]]
[[18  8]
 [42 18]]


In [34]:
 # when usinhg matrix and scalar
print(a-10) # boardcasting
print(a*10) 
print(a/10)
print(a+10)

[[-9 -8]
 [-7 -6]]
[[10 20]
 [30 40]]
[[0.1 0.2]
 [0.3 0.4]]
[[11 12]
 [13 14]]


In [35]:
 # indexing
print(a[0,0])
print(a[-1,-1])

array([1, 2])

In [37]:
# slicing
x = np.random.randint(1,10,(5,5))
print(x)
print(x[:,0]) # first column
print(x[:,-1]) # last column
print(x[:,:3]) #  first  3 column

[[6 4 8 1 4]
 [2 9 2 4 6]
 [7 7 5 1 4]
 [1 9 1 5 7]
 [8 9 4 1 6]]
[6 2 7 1 8]
[4 6 4 7 6]
[[6 4 8]
 [2 9 2]
 [7 7 5]
 [1 9 1]
 [8 9 4]]
