In [1]:
import numpy as np

In [4]:
x = [[1,2],[3,4]]
nx = np.array(x)


In [5]:
print(nx.sum())
print(nx.min())
print(nx.mean())
print(nx.std())
print(nx.var())

10
1
2.5
1.118033988749895
1.25


In [ ]:
type(nx)


In [6]:
nx.shape

(2, 2)

In [11]:
print(nx.shape)  # shape of matrix
print(nx.size)   # total element
print(nx.dtype) # type of element

(2, 2)
4
int64


In [7]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(a)
print(a.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
(3, 3)


functionsto creat matrix
- 'arrange': creat a range of numbers
- linspace: create a mtrix of specified number of element
- ones : create a matrix of ones
- zeros: create a matrix  of zeros
- random.randint: create a mtrix of random integers
- random.rand: create a matrix of randon element
- diag : create a matrix with diagonal element

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [ ]:
a = np.arange(1,50)
print(a)

In [12]:
np.arange(1,2,.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [13]:
np.linspace(1,2,10)


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [14]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.random.randint(1,100,10)


array([13, 54,  3, 36, 86, 83, 34, 17, 12, 74], dtype=int32)

In [24]:
np.random.randint(-5,6,(5,5))

array([[ 4,  0, -2,  5, -3],
       [-2, -5,  0, -1, -1],
       [-3, -2, -1, -5,  1],
       [ 2,  3,  0, -2, -2],
       [ 3, -3,  1,  3, -1]], dtype=int32)

In [25]:
np.random.rand(5)

array([0.21602037, 0.22750342, 0.59847441, 0.99428234, 0.03637265])

In [27]:
np.random.rand(5,5)

array([[0.83571305, 0.33589334, 0.69644865, 0.56421622, 0.71783287],
       [0.7640806 , 0.3611404 , 0.02814355, 0.79642331, 0.83902301],
       [0.35484057, 0.54173298, 0.20079564, 0.71599277, 0.99610021],
       [0.559121  , 0.0869653 , 0.477017  , 0.73244842, 0.91090297],
       [0.83526302, 0.49938276, 0.56365229, 0.45717629, 0.21510857]])

In [29]:
np.set_printoptions(precision=3)
np.random.rand(10,5)

array([[0.89 , 0.191, 0.323, 0.876, 0.313],
       [0.762, 0.701, 0.081, 0.817, 0.872],
       [0.871, 0.719, 0.922, 0.538, 0.79 ],
       [0.855, 0.348, 0.972, 0.28 , 0.786],
       [0.754, 0.155, 0.776, 0.899, 0.668],
       [0.691, 0.467, 0.303, 0.754, 0.936],
       [0.109, 0.199, 0.188, 0.722, 0.261],
       [0.579, 0.689, 0.79 , 0.554, 0.71 ],
       [0.56 , 0.708, 0.031, 0.159, 0.757],
       [0.731, 0.404, 0.159, 0.133, 0.178]])

In [30]:
x = [1,2,3,45,6]
np.diag(x)

array([[ 1,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 0,  0,  0, 45,  0],
       [ 0,  0,  0,  0,  6]])

In [32]:
# reshape
np.arange(10).reshape(5,2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
x = np.linspace(1,5,25).reshape(5,5)

In [39]:
x.flatten()

array([1.   , 1.167, 1.333, 1.5  , 1.667, 1.833, 2.   , 2.167, 2.333,
       2.5  , 2.667, 2.833, 3.   , 3.167, 3.333, 3.5  , 3.667, 3.833,
       4.   , 4.167, 4.333, 4.5  , 4.667, 4.833, 5.   ])

In [40]:
y = np.arange(1,26).reshape(5,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [42]:
y.T

array([[ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24],
       [ 5, 10, 15, 20, 25]])

In [45]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

[[4 7 2]
 [1 7 3]
 [3 8 6]]
[[5 8 2]
 [5 1 6]
 [9 8 5]]


In [46]:
a+b

array([[ 9, 15,  4],
       [ 6,  8,  9],
       [12, 16, 11]], dtype=int32)

In [47]:
a.dot(b) #dot product (matrix multiplication)

array([[ 73,  55,  60],
       [ 67,  39,  59],
       [109,  80,  84]], dtype=int32)

In [48]:
a-b

array([[-1, -1,  0],
       [-4,  6, -3],
       [-6,  0,  1]], dtype=int32)

In [49]:
a+10

array([[14, 17, 12],
       [11, 17, 13],
       [13, 18, 16]], dtype=int32)

In [50]:
a/b

array([[0.8  , 0.875, 1.   ],
       [0.2  , 7.   , 0.5  ],
       [0.333, 1.   , 1.2  ]])

- stats

In [52]:
print(a.mean())

4.555555555555555


In [54]:
print(a.mean())
print(a.mean(axis=0)) # column wise mean
print(a.mean(axis=1)) # row wise mean

4.555555555555555
[2.667 7.333 3.667]
[4.333 3.667 5.667]


In [55]:
print(a.sum())
print(a.sum(axis=0)) # column wise mean
print(a.sum(axis=1))

41
[ 8 22 11]
[13 11 17]


In [56]:
np.sin(a)

array([[-0.757,  0.657,  0.909],
       [ 0.841,  0.657,  0.141],
       [ 0.141,  0.989, -0.279]])

In [58]:
print(np.cos(a))
print(np.tan(a))

[[-0.654  0.754 -0.416]
 [ 0.54   0.754 -0.99 ]
 [-0.99  -0.146  0.96 ]]
[[ 1.158  0.871 -2.185]
 [ 1.557  0.871 -0.143]
 [-0.143 -6.8   -0.291]]


In [59]:
print(np.exp(a))
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[5.460e+01 1.097e+03 7.389e+00]
 [2.718e+00 1.097e+03 2.009e+01]
 [2.009e+01 2.981e+03 4.034e+02]]
[[2.    2.646 1.414]
 [1.    2.646 1.732]
 [1.732 2.828 2.449]]
8
1


In [60]:
z = np.random.randint(1,100,(2,5))
print(z)

[[96  5 68 26 19]
 [66 85 52 75 64]]


In [63]:
print(x.max())
print(x.argmax())
print(x.min())
print(x.argmin())

5.0
24
1.0
0
